FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# App update

## feature1 [/builds/feature1]
### update [GET]
+ Response 200 (application/json)

        {"latestBuildNumber":"4","url":"https://dl.dropboxusercontent.com/s/ukdkxb7qhtsxuuc/manifest.plist","description":"description about latest update"}